# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/metrics_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/metrics_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/metrics_config.proto\x12\x0flczero.training\"\x0f\n\rTrainingBatch\"\xf5\x01\n\x0cMetricConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\ruse_swa_model\x18\x02 \x01(\x08\x12\x11\n\x06period\x18\x03 \x01(\x05:\x01\x31\x12\x1f\n\x10use_global_steps\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x0b\x61\x66ter_epoch\x18\x05 \x01(\x08\x12\x38\n\x0etraining_batch\x18\x06 \x01(\x0b\x32\x1e.lczero.training.TrainingBatchH\x00\x12\x1b\n\x11\x64\x61taloader_output\x18\x07 \x01(\tH\x00\x12\x16\n\x0cnpz_filename\x18\x08 \x01(\tH\x00\x42\x08\n\x06sample\"X\n\rMetricsConfig\x12\x18\n\x10tensorboard_path\x18\x01 \x01(\t\x12-\n\x06metric\x18\x02 \x03(\x0b\x32\x1d.lczero.training.MetricConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.metrics_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGBATCH']._serialized_start=47
  _globals['_TRAININGBATCH']._serialized_end=62
  _globals['_METRICCONFIG']._serialized_start=65
  _globals['_METRICCONFIG']._serialized_end=310
  _globals['_METRICSCONFIG']._serialized_start=312
  _globals['_METRICSCONFIG']._serialized_end=400
# @@protoc_insertion_point(module_scope)
