# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/model_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/model_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import net_pb2 as proto_dot_net__pb2
from proto import hlo_pb2 as proto_dot_hlo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/model_config.proto\x12\x0flczero.training\x1a\x0fproto/net.proto\x1a\x0fproto/hlo.proto\"\xd2\x02\n\x0bModelConfig\x12\x31\n\x08\x64\x65\x66\x61ults\x18\x04 \x01(\x0b\x32\x1f.lczero.training.DefaultsConfig\x12\x33\n\tembedding\x18\x05 \x01(\x0b\x32 .lczero.training.EmbeddingConfig\x12/\n\x07\x65ncoder\x18\x06 \x01(\x0b\x32\x1e.lczero.training.EncoderConfig\x12\x36\n\x0bpolicy_head\x18\x07 \x01(\x0b\x32!.lczero.training.PolicyHeadConfig\x12\x34\n\nvalue_head\x18\x08 \x01(\x0b\x32 .lczero.training.ValueHeadConfig\x12<\n\x0emovesleft_head\x18\t \x01(\x0b\x32$.lczero.training.MovesLeftHeadConfig\"\xc9\x01\n\x0e\x44\x65\x66\x61ultsConfig\x12\x33\n\rcompute_dtype\x18\x02 \x01(\x0e\x32\x1c.pblczero.XlaShapeProto.Type\x12>\n\nactivation\x18\x04 \x01(\x0e\x32*.pblczero.NetworkFormat.ActivationFunction\x12\x42\n\x0e\x66\x66n_activation\x18\x05 \x01(\x0e\x32*.pblczero.NetworkFormat.ActivationFunction\"J\n\x0f\x45mbeddingConfig\x12\x12\n\ndense_size\x18\x01 \x01(\r\x12\x16\n\x0e\x65mbedding_size\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x66\x66\x18\x03 \x01(\r\"\x81\x01\n\rEncoderConfig\x12\x12\n\nnum_blocks\x18\x03 \x01(\r\x12\x0b\n\x03\x64\x66\x66\x18\x04 \x01(\r\x12\x0f\n\x07\x64_model\x18\x05 \x01(\r\x12\r\n\x05heads\x18\x06 \x01(\r\x12/\n\x07smolgen\x18\t \x01(\x0b\x32\x1e.lczero.training.SmolgenConfig\"\x8f\x01\n\rSmolgenConfig\x12\x17\n\x0fhidden_channels\x18\x01 \x01(\r\x12\x13\n\x0bhidden_size\x18\x02 \x01(\r\x12\x10\n\x08gen_size\x18\x03 \x01(\r\x12>\n\nactivation\x18\x05 \x01(\x0e\x32*.pblczero.NetworkFormat.ActivationFunction\";\n\x10PolicyHeadConfig\x12\x16\n\x0e\x65mbedding_size\x18\x01 \x01(\r\x12\x0f\n\x07\x64_model\x18\x02 \x01(\r\"\'\n\x0fValueHeadConfig\x12\x14\n\x0cnum_channels\x18\x01 \x01(\r\"+\n\x13MovesLeftHeadConfig\x12\x14\n\x0cnum_channels\x18\x01 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.model_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELCONFIG']._serialized_start=80
  _globals['_MODELCONFIG']._serialized_end=418
  _globals['_DEFAULTSCONFIG']._serialized_start=421
  _globals['_DEFAULTSCONFIG']._serialized_end=622
  _globals['_EMBEDDINGCONFIG']._serialized_start=624
  _globals['_EMBEDDINGCONFIG']._serialized_end=698
  _globals['_ENCODERCONFIG']._serialized_start=701
  _globals['_ENCODERCONFIG']._serialized_end=830
  _globals['_SMOLGENCONFIG']._serialized_start=833
  _globals['_SMOLGENCONFIG']._serialized_end=976
  _globals['_POLICYHEADCONFIG']._serialized_start=978
  _globals['_POLICYHEADCONFIG']._serialized_end=1037
  _globals['_VALUEHEADCONFIG']._serialized_start=1039
  _globals['_VALUEHEADCONFIG']._serialized_end=1078
  _globals['_MOVESLEFTHEADCONFIG']._serialized_start=1080
  _globals['_MOVESLEFTHEADCONFIG']._serialized_end=1123
# @@protoc_insertion_point(module_scope)
