# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/stage_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/stage_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/stage_control.proto\x12\x0flczero.training\"X\n ShufflingChunkPoolControlRequest\x12\x1a\n\x12reset_chunk_anchor\x18\x01 \x01(\x08\x12\x18\n\x10set_chunk_anchor\x18\x02 \x01(\t\"d\n\x13StageControlRequest\x12M\n\x12\x63hunk_pool_request\x18\x01 \x01(\x0b\x32\x31.lczero.training.ShufflingChunkPoolControlRequest\"V\n!ShufflingChunkPoolControlResponse\x12\x14\n\x0c\x63hunk_anchor\x18\x01 \x01(\t\x12\x1b\n\x13\x63hunks_since_anchor\x18\x02 \x01(\x05\"g\n\x14StageControlResponse\x12O\n\x13\x63hunk_pool_response\x18\x01 \x01(\x0b\x32\x32.lczero.training.ShufflingChunkPoolControlResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.stage_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHUFFLINGCHUNKPOOLCONTROLREQUEST']._serialized_start=46
  _globals['_SHUFFLINGCHUNKPOOLCONTROLREQUEST']._serialized_end=134
  _globals['_STAGECONTROLREQUEST']._serialized_start=136
  _globals['_STAGECONTROLREQUEST']._serialized_end=236
  _globals['_SHUFFLINGCHUNKPOOLCONTROLRESPONSE']._serialized_start=238
  _globals['_SHUFFLINGCHUNKPOOLCONTROLRESPONSE']._serialized_end=324
  _globals['_STAGECONTROLRESPONSE']._serialized_start=326
  _globals['_STAGECONTROLRESPONSE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
